Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CentroAutomotivo.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CentroAutomotivo.Data;
using CentroAutomotivo.Models;
using Microsoft.AspNetCore.Authorization;

namespace CentroAutomotivo.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class MarcaController : Controller
    {
        private readonly AppDbContext _context;

        public MarcaController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Marca
        public async Task<IActionResult> Index()
        {
            return View(await _context.Marcas.ToListAsync());
        }

        // GET: Marca/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Marcas == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (marca == null)
            {
                return NotFound();
            }

            return View(marca);
        }

        // GET: Marca/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Marca/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome")] Marca marca)
        {
            if (ModelState.IsValid)
            {
                _context.Add(marca);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(marca);
        }

        // GET: Marca/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Marcas == null)
            {
                return NotFound();
            }

            var marca = await _context.Marcas.FindAsync(id);
            if (marca == null)
            {
                return NotFound();
            }
            return View(marca);
        }

        // POST: Marca/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome")] Marca marca)
        {
            if (id != marca.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(marca);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MarcaExists(marca.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(marca);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var marca = await _context.Marcas.FirstOrDefaultAsync(m => m.Id == id);

            if (marca == null)
            {
                return Json(new { success = false, message = "Marca não encontrada!" });
            }

            try
            {
                _context.Marcas.Remove(marca);
                await _context.SaveChangesAsync();
            }
            catch
            {
                return Json(new { success = false, message = "Ocorreu um problema inesperado! Avise ao Suporte!" });
            }

            return Json(new { success = true, message = "Marca excluída com sucesso!" });
        }

        private bool MarcaExists(int id)
        {
            return _context.Marcas.Any(e => e.Id == id);
        }
    }
}

Controllers/ModeloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CentroAutomotivo.Data;
using CentroAutomotivo.Models;
using Microsoft.AspNetCore.Authorization;

namespace CentroAutomotivo.Controllers
{
    [Authorize]
    public class ModeloController : Controller
    {
        private readonly AppDbContext _context;

        public ModeloController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Modelo
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Modelos.Include(m => m.Marca);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Modelo/Details/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Modelos == null)
            {
                return NotFound();
            }

            var modelo = await _context.Modelos
                .Include(m => m.Marca)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (modelo == null)
            {
                return NotFound();
            }

            return View(modelo);
        }

        // GET: Modelo/Create
        [Authorize(Roles = "Administrador")]
        public IActionResult Create()
        {
            ViewData["MarcaId"] = new SelectList(_context.Marcas, "Id", "Nome");
            return View();
        }

        // POST: Modelo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Ano,MarcaId")] Modelo modelo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(modelo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MarcaId"] = new SelectList(_context.Marcas, "Id", "Nome", modelo.MarcaId);
            return View(modelo);
        }

        // GET: Modelo/Edit/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Modelos == null)
            {
                return NotFound();
            }

            var modelo = await _context.Modelos.FindAsync(id);
            if (modelo == null)
            {
                return NotFound();
            }
            ViewData["MarcaId"] = new SelectList(_context.Marcas, "Id", "Nome", modelo.MarcaId);
            return View(modelo);
        }

        // POST: Modelo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Ano,MarcaId")] Modelo modelo)
        {
            if (id != modelo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(modelo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModeloExists(modelo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MarcaId"] = new SelectList(_context.Marcas, "Id", "Nome", modelo.MarcaId);
            return View(modelo);
        }

        [Authorize(Roles = "Administrador")]
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var modelo = await _context.Modelos.FirstOrDefaultAsync(m => m.Id == id);

            if (modelo == null)
            {
                return Json(new { success = false, message = "Modelo não encontrado!" });
            }

            try
            {
                _context.Modelos.Remove(modelo);
                await _context.SaveChangesAsync();
            }
            catch
            {
                return Json(new { success = false, message = "Ocorreu um problema inesperado! Avise ao Suporte!" });
            }

            return Json(new { success = true, message = "Modelo excluído com sucesso!" });
        }

        // GET: Modelo/Delete/5
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Modelos == null)
            {
                return NotFound();
            }

            var modelo = await _context.Modelos
                .Include(m => m.Marca)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (modelo == null)
            {
                return NotFound();
            }

            return View(modelo);
        }

        // POST: Modelo/Delete/5
        [Authorize(Roles = "Administrador")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Modelos == null)
            {
                return Problem("Entity set 'AppDbContext.Modelos'  is null.");
            }
            var modelo = await _context.Modelos.FindAsync(id);
            if (modelo != null)
            {
                _context.Modelos.Remove(modelo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> ObterModelo(int id)
        {
            var modelo = await _context.Modelos.Include(m => m.Marca).FirstOrDefaultAsync(m => m.Id == id);
            modelo.Marca.Modelos = null;

            return Json(modelo);
        }

        private bool ModeloExists(int id)
        {
            return _context.Modelos.Any(e => e.Id == id);
        }
    }
}

Controllers/PecaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CentroAutomotivo.Data;
using CentroAutomotivo.Models;
using Microsoft.AspNetCore.Authorization;

namespace CentroAutomotivo.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class PecaController : Controller
    {
        private readonly AppDbContext _context;

        public PecaController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Peca
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pecas.ToListAsync());
        }

        // GET: Peca/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pecas == null)
            {
                return NotFound();
            }

            var peca = await _context.Pecas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (peca == null)
            {
                return NotFound();
            }

            return View(peca);
        }

        public async Task<JsonResult> ObterPeca(int? id)
        {
            if (id == null || _context.Pecas == null)
            {
                return Json(new { message = "Id inválido" });
            }

            var peca = await _context.Pecas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (peca == null)
            {
                return Json(new { message = "Peça não encontrada" });
            }

            return Json(peca);
        }

        // GET: Peca/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Peca/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Quantidade,Preco")] Peca peca)
        {
            if (ModelState.IsValid)
            {
                _context.Add(peca);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(peca);
        }

        // GET: Peca/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pecas == null)
            {
                return NotFound();
            }

            var peca = await _context.Pecas.FindAsync(id);
            if (peca == null)
            {
                return NotFound();
            }
            return View(peca);
        }

        // POST: Peca/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Quantidade,Preco")] Peca peca)
        {
            if (id != peca.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(peca);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PecaExists(peca.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(peca);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var peca = _context.Pecas.FirstOrDefault(s => s.Id == id);

            if (peca == null)
            {
                return Json(new { success = false, message = "Peça não encontrada!" });
            }

            try
            {
                _context.Pecas.Remove(peca);
                await _context.SaveChangesAsync();
            }
            catch
            {
                return Json(new { success = false, message = "Ocorreu um problema inesperado! Avise ao Suporte!" });
            }

            return Json(new { success = true, message = "Peça excluída com sucesso!" });
        }

        private bool PecaExists(int id)
        {
            return _context.Pecas.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>@ViewData["Title"] - JAVA Centro Automotivo</title>
  <!--favicon-->
  <link type="image/png" sizes="16x16" rel="icon" href="~/assets/img/icons8-carro-16.png">
  <!-- Vector CSS -->
  <link href="~/admin/assets/plugins/vectormap/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
  <!-- simplebar CSS-->
  <link href="~/admin/assets/plugins/simplebar/css/simplebar.css" rel="stylesheet" />
  <!-- Bootstrap core CSS-->
  <link href="~/admin/assets/css/bootstrap.min.css" rel="stylesheet" />
  <!-- animate CSS-->
  <link href="~/admin/assets/css/animate.css" rel="stylesheet" type="text/css" />
  <!-- Icons CSS-->
  <link href="~/admin/assets/css/icons.css" rel="stylesheet" type="text/css" />
  <!-- Sidebar CSS-->
  <link href="~/admin/assets/css/sidebar-menu.css" rel="stylesheet" />
  <!-- Custom Style-->
  <link href="~/admin/assets/css/app-style.css" rel="stylesheet" />

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
  <link href="~/css/site.css" rel="stylesheet">
  @await RenderSectionAsync("Styles", required: false)

</head>

<body class="bg-theme bg-theme9">

  <!-- Start wrapper-->
  <div id="wrapper">

    <!--Start sidebar-wrapper-->
    <div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">
      <div class="brand-logo">
        <a asp-controller="Admin" asp-action="Index">
          <img src="~/assets/img/logo.png" style="width: 45%;" class="logo-icon" alt="logo icon">
        </a>
      </div>
      <ul class="sidebar-menu do-nicescrol">
        <li class="@(ViewBag.Title == "Área Administrativa" ? "active" : "")">
          <a asp-controller="Admin" asp-action="Index" style="display: flex; justify-content: start; align-items: center;">
            <span class="material-icons mr-2">
              dashboard
            </span> <span>Dashboard</span>
          </a>
        </li>
        <li class="@(ViewBag.Title == "Ordens de Serviço" || ViewBag.Title == "Adicionar Ordem de Serviço" || ViewBag.Title == "Editar Ordem de Serviço" || 
                     ViewBag.Title == "Excluir Ordem de Serviço" || ViewBag.Title == "Detalhes Ordem de Serviço" ||
                     ViewBag.Title == "Selecionar Usuário" || ViewBag.Title == "Selecionar Veículo" ? "active" : "")">
          <a asp-controller="OrdemServico" asp-action="Index" style="display: flex; justify-content: start; align-items: center;">
            <span class="material-icons mr-2">
              receipt_long
            </span> <span>Ordens de Serviço</span>
          </a>
        </li>

        <li class="@(ViewBag.Title == "Agendamentos" || ViewBag.Title == "Editar Agendamento" || 
                     ViewBag.Title == "Detalhes Agendamento" ? "active" : "")">
          <a asp-controller="Agendamento" asp-action="Index" style="display: flex; justify-content: start; align-items: center;">
            <span class="material-symbols-outlined mr-2">
              calendar_month
            </span> <span>Agendamentos</span>
          </a>
        </li>

        <li class="@(ViewBag.Title == "Veículos" || ViewBag.Title == "Adicionar Veículo" || ViewBag.Title == "Editar Veículo" || 
                     ViewBag.Title == "Excluir Veículo" || ViewBag.Title == "Detalhes Veículo" ? "active" : "")">
          <a asp-controller="Veiculo" asp-action="Index" style="display: flex; justify-content: start; align-items: center;">
            <span class="material-icons mr-2">drive_eta</span> <span>Veículos</span>
          </a>
        </li>

        <li class="@(ViewBag.Title == "Modelos" || ViewBag.Title == "Adicionar Modelo" || ViewBag.Title == "Editar Modelo" || 
                     ViewBag.Title == "Excluir Modelo" || ViewBag.Title == "Detalhes Modelo" ? "active" : "")">
          <a asp-controller="Modelo" asp-action="Index" style="display: flex; justify-content: start; align-items: center;">
            <span class="material-icons mr-2">
              airport_shuttle
            </span> <span>Modelos</span>
          </a>
        </li>

        <li class="@(ViewBag.Title == "Marcas" || ViewBag.Title == "Adicionar Marca" || ViewBag.Title == "Editar Marca" || 
                     ViewBag.Title == "Excluir Marca" || ViewBag.Title == "Detalhes Marca" ? "active" : "")">
          <a asp-controller="Marca" asp-action="Index" style="display: flex; justify-content: start; align-items: center;">
            <span class="material-symbols-outlined mr-2">
              copyright
            </span> <span>Marcas</span>
          </a>
        </li>

        <li class="@(ViewBag.Title == "Peças" || ViewBag.Title == "Adicionar Peça" || ViewBag.Title == "Editar Peça" || 
                     ViewBag.Title == "Excluir Peça" || ViewBag.Title == "Detalhes Peça" ? "active" : "")">
          <a asp-controller="Peca" asp-action="Index" style="display: flex; justify-content: start; align-items: center;">
            <span class="material-icons mr-2">
              build
            </span> <span>Peças</span>
          </a>
        </li>

        <li class="@(ViewBag.Title == "Serviços" || ViewBag.Title == "Adicionar Serviço" || ViewBag.Title == "Editar Serviço" || 
                     ViewBag.Title == "Excluir Serviço" || ViewBag.Title == "Detalhes Serviço" ? "active" : "")">
          <a asp-controller="Servico" asp-action="Index" style="display: flex; justify-content: start; align-items: center;">
            <span class="material-icons mr-2">
              miscellaneous_services
            </span> <span>Serviços</span>
          </a>
        </li>

        <li class="@(ViewBag.Title == "Status" || ViewBag.Title == "Adicionar Status" || ViewBag.Title == "Editar Status" || 
                     ViewBag.Title == "Excluir Status" || ViewBag.Title == "Detalhes Status" ? "active" : "")">
          <a asp-controller="StatusOrdemServico" asp-action="Index" style="display: flex; justify-content: start; align-items: center;">
            <span class="material-icons mr-2">
              battery_5_bar
            </span> <span>Status</span>
          </a>
        </li>

        <li class="@(ViewBag.Title == "Tipos Status" || ViewBag.Title == "Adicionar Tipo Status" || ViewBag.Title == "Editar Tipo Status" || 
                     ViewBag.Title == "Excluir Tipo Status" || ViewBag.Title == "Detalhes Tipo Status" ? "active" : "")">
          <a asp-controller="TipoStatus" asp-action="Index" style="display: flex; justify-content: start; align-items: center;">
            <span class="material-symbols-outlined mr-2">
              format_list_numbered
            </span> <span>Tipo Status</span>
          </a>
        </li>

      </ul>

    </div>
    <!--End sidebar-wrapper-->

    <!--Start topbar header-->
    <header class="topbar-nav">
      <nav class="navbar navbar-expand fixed-top">
        <ul class="navbar-nav mr-auto align-items-center">
          <li class="nav-item">
            <a class="nav-link toggle-menu" href="javascript:void();">
              <i class="icon-menu menu-icon"></i>
            </a>
          </li>
        </ul>

        <ul class="navbar-nav align-items-center right-nav-link">
          <li class="nav-item dropdown-lg">
            <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown"
              href="javascript:void();">
              <i class="fa fa-envelope-open-o"></i></a>
          </li>
          <li class="nav-item dropdown-lg">
            <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown"
              href="javascript:void();">
              <i class="fa fa-bell-o"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" data-toggle="dropdown" href="#">
              @{
                var user = UserManager.GetUserAsync(User).Result;
                var picture = user.FotoPerfil ?? "~/avatars/nopicture.png";
              }
              <span class="user-profile"><img src="@Url.Content(picture)" class="img-circle" alt="user avatar"></span>
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item user-details">
                <a href="javaScript:void();">
                  <div class="media">
                    <div class="avatar"><img class="align-self-start mr-3" src="@Url.Content(picture)"
                        alt="user avatar"></div>
                    <div class="media-body">
                      <h6 class="mt-2 user-title">@user.Nome</h6>
                      <p class="user-subtitle">@user.Email</p>
                    </div>
                  </div>
                </a>
              </li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item">
                <a asp-controller="Cliente" asp-action="Index"><i class="ti-face-smile mr-2"></i>Área do Cliente</a>
              </li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item">
                <a asp-controller="Admin" asp-action="Index"><i class="ti-desktop mr-2"></i>Área Administrativa</a>
              </li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item">
                <a asp-area="Identity" asp-page="/Account/Manage/Index"><i class="ti-user mr-2"></i>Meu Perfil</a>
              </li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item">
                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout"
                  asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                  <button type="submit" class="btn text-danger">Sair</button>
                </form>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
    </header>
    <!--End topbar header-->

    <div class="clearfix"></div>

    <div class="content-wrapper">
      <div class="container-fluid">

        @RenderBody()

        <div class="overlay toggle-menu"></div>

      </div>
      <!-- End container-fluid-->
    </div><!--End content-wrapper-->
    <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->

    <!--Start footer-->
    <footer class="footer">
      <div class="container">
        <div class="text-center">
          Copyright © 2023 JAVA Centro Automotivo
        </div>
      </div>
    </footer>
    <!--End footer-->

    <!--start color switcher-->
    <div class="right-sidebar">
      <div class="switcher-icon">
        <i class="zmdi zmdi-settings zmdi-hc-spin"></i>
      </div>
      <div class="right-sidebar-content">

        <p class="mb-0">Gaussion Texture</p>
        <hr>

        <ul class="switcher">
          <li id="theme1"></li>
          <li id="theme2"></li>
          <li id="theme3"></li>
          <li id="theme4"></li>
          <li id="theme5"></li>
          <li id="theme6"></li>
        </ul>

        <p class="mb-0">Gradient Background</p>
        <hr>

        <ul class="switcher">
          <li id="theme7"></li>
          <li id="theme8"></li>
          <li id="theme9"></li>
          <li id="theme10"></li>
          <li id="theme11"></li>
          <li id="theme12"></li>
          <li id="theme13"></li>
          <li id="theme14"></li>
          <li id="theme15"></li>
        </ul>

      </div>
    </div>
    <!--end color switcher-->

  </div><!--End wrapper-->

  <!-- Bootstrap core JavaScript-->
  <script src="~/admin/assets/js/jquery.min.js"></script>
  <script src="~/admin/assets/js/popper.min.js"></script>
  <script src="~/admin/assets/js/bootstrap.min.js"></script>

  <!-- simplebar js -->
  <script src="~/admin/assets/plugins/simplebar/js/simplebar.js"></script>
  <!-- sidebar-menu js -->
  <script src="~/admin/assets/js/sidebar-menu.js"></script>
  <!-- loader scripts -->
  @* <script src="~/admin/assets/js/jquery.loading-indicator.js"></script> *@
  <!-- Custom scripts -->
  <script src="~/admin/assets/js/app-script.js"></script>
  <!-- Chart js -->

  <script src="~/admin/assets/plugins/Chart.js/Chart.min.js"></script>

  <!-- Index js -->
  <script src="~/admin/assets/js/index.js"></script>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <!-- Mask -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://rawgit.com/RobinHerbots/Inputmask/5.x/dist/jquery.inputmask.js"></script>
  <script src="~/js/site.js"></script>
  @await RenderSectionAsync("Scripts", required: false)

</body>

</html>